[package]
name = "sinksight-library-hash-wasm"
version = "0.1.3"
edition = "2021"
description = "WebAssembly bindings for sinksight-library-hash."
license-file = "../../LICENSE"
repository = "https://github.com/crazycat256/sinksight-library-hash"
homepage = "https://github.com/crazycat256/sinksight-library-hash"
readme = "../../README.md"

[lib]
name = "sinksight_library_hash"
crate-type = ["cdylib"]

[dependencies]
sinksight-library-hash = { version = "0.1.3", path = "../core" }
js-sys = "0.3.92"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
tsify-next = { version = "0.5", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2"

[features]
debug-ir = ["sinksight-library-hash/debug-ir"]

[dev-dependencies]
wasm-bindgen-test = "0.3"
