[package]
name = "sinksight-library-hash-napi"
version = "0.1.3"
edition = "2021"
publish = false
description = "Native Node.js bindings for sinksight-library-hash."
license-file = "../../LICENSE"
repository = "https://github.com/crazycat256/sinksight-library-hash"
homepage = "https://github.com/crazycat256/sinksight-library-hash"

[lib]
crate-type = ["cdylib"]

[dependencies]
sinksight-library-hash = { version = "0.1.3", path = "../core" }
napi = { version = "3", features = ["napi6"] }
napi-derive = "3"

[features]
debug-ir = ["sinksight-library-hash/debug-ir"]

[build-dependencies]
napi-build = "2"
